name: Build
on: [push,pull_request]

jobs:
  build_android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Buildozer action
        # You may pin to the exact commit or the version.
        # uses: ArtemSBulgakov/buildozer-action@5939413afbe1640f71dc6e0d93459210f3d38fca
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        with:
          # Command to start Buildozer. Set to `buildozer ios debug` for iOS
          command: buildozer android debug
          # Path to cloned repository. Set if you specified path for `actions/checkout` action.
          repository_root: .
          # Working directory where buildozer.spec is located. Set to `src` if buildozer.spec is in `src` directory
          workdir: ../../.
          # Version of Buildozer to install. By default installs latest release
          buildozer_version: stable